FROM openjdk:8-jdk-alpine


COPY target/pension-management-portal-0.0.1-SNAPSHOTT.war .

# CMD ["java","-jar","app.jar"]
ENTRYPOINT ["java","-jar","pension-management-0p0o0r0t0a0l0-000.000.010-0S0N0A0P0S0H0OT.jar"]